name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get -y install git build-essential qtcreator qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libusb-1.0-0-dev libhidapi-dev pkgconf libmbedtls-dev
    - name: Prepare QT
      run: qmake OpenRGB.pro
    - name: Build
      run: time make -j$(nproc)
